require 'cocoapods-dependency-graph/gem_version'
require 'cocoapods'
require 'fileutils'
require_relative 'cocoapods-dependency-graph/generator/excel-generator'

module Dependency
  class Graph
    # @param [Array<UmbrellaTargetDescription>] The list of
    #         the CocoaPods umbrella targets generated by the installer.
    #
    def generate(umbrella_targets)
      unless umbrella_targets.length() > 0
        puts "No target detected"
      end

      umbrella_target = umbrella_targets[0]
      puts "***** TARGET #{umbrella_target.cocoapods_target_label}"
      
      module_spec_hash = {}
      umbrella_target.specs.each { | spec |
        module_spec_hash[spec.module_name] = spec
      } 

      excel_generator = DependencyExcel.new.generate(umbrella_target, module_spec_hash)
      
      puts "#{umbrella_target.platform_name}"
      puts "#{umbrella_target.platform_deployment_target}"  
    end
  end
end