require 'cocoapods-dependency-graph/gem_version'
require 'cocoapods'
require 'fileutils'
require_relative 'cocoapods-dependency-graph/generator/excel_generator'
require_relative 'cocoapods-dependency-graph/generator/json_generator'
require_relative 'cocoapods-dependency-graph/generator/graph_generator'

module Dependency
  class Graph
    # @param [Array<UmbrellaTargetDescription>] The list of
    #         the CocoaPods umbrella targets generated by the installer.
    #
    def generate(umbrella_targets)
      unless umbrella_targets.length() > 0
        puts "No target detected"
      end

      umbrella_target = umbrella_targets[0]
      
      module_spec_hash = {}
      umbrella_target.specs.each { | spec |
        module_spec_hash[spec.name] = spec
      } 

      ExcelGenerator.new.generate(umbrella_target)
      JsonGenerator.new.generate(umbrella_target, module_spec_hash)
      GraphGenerator.new.generate(umbrella_target, module_spec_hash)      
    end
  end
end