require 'cocoapods-dependency-graph/gem_version'
require 'cocoapods'
require 'fileutils'
module Dependency
  class Graph
    # @return [Array<UmbrellaTargetDescription>] The list of
    #         the CocoaPods umbrella targets generated by the installer.
    #
    def generate(umbrella_targets)
      # Iterate the array of UmbrellaTargetDescription
      umbrella_targets.each { | umbrella_target |
        puts "*****#{umbrella_target.cocoapods_target_label}"
        umbrella_target.specs.each { | spec |
          puts "umbrella target == #{spec.name}"
          puts "module name ==#{spec.module_name}"
          puts "source: #{spec.source}"
          puts "version: #{spec.version}"
          puts "homepage: #{spec.homepage}"
          puts "subspec: #{spec.subspecs}"
          if spec.source
            puts "local: #{spec.local?}"
          end
          puts "des #{spec.root.attributes_hash['summary']}"
          # dependency 
          puts "-------all_dependencies-----"
          spec.dependencies.each { | dependency |
            puts "#{dependency.name}"
            puts "#{dependency.podspec_repo}"
            puts "#{dependency.specific_version}"
          }
        } 
        puts "#{umbrella_target.platform_name}"
        puts "#{umbrella_target.platform_deployment_target}"
      }
    end
  end
end