require 'fast_excel'

module Dependency 
  class DependencyExcel 
    attr_accessor :module_spec_hash 

    attr_accessor :workbook
    attr_accessor :worksheet
  
    def create_excel 
      @workbook = FastExcel.open("cocoapods-dependency-list.xlsx", constant_memory: true)
      @worksheet = workbook.add_worksheet("cocoapods-dependency-list")
    end

    def create_title()
      @worksheet.append_row(["module name", "local", "source", "version", "homepage", "summary"], @workbook.bold_format)
    end

    def create_row(spec) 
      local = spec.local? if spec.source
      summary = spec.root.attributes_hash['summary']
      worksheet << [spec.module_name, local, spec.source, spec.version, spec.homepage, summary]
    end

    # @param [Array<Specification>] specs a list specification
    def create_content(specs) 
      specs.each { | spec | 
        create_row(spec)
      } 
    end

    def close_excel 
      @workbook.close
    end
    
    # @param  [UmbrellaTargetDescription] umbrella_target the CocoaPods umbrella targets generated by the installer.
    # @param  [Hash{<String, Specification>}] module_spec_hash 
    #
    def generate(umbrella_target, module_spec_hash)
      create_excel
      create_title
      create_content(umbrella_target.specs)
      close_excel
    end 
  end
end
