# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
plugin 'cocoapods-dependency-graph'

target 'DependencyGraphDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DependencyGraphDemo
  pod 'Alamofire', '~> 5.2'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'lottie-ios'
  pod 'SVProgressHUD'

  target 'DependencyGraphDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DependencyGraphDemoUITests' do
    # Pods for testing
  end

end
